### PR TITLE
Create 2017-03-16-ComputerFraudandAbuseAct.md

### PR DESCRIPTION
**Pull request by jonathanchamberlain**
Notes from guest lecture on 16 March 2017

### CODE REVIEW

**Comment by sean-smith** [comment]
Can you move this file into _posts. Thanks

**Comment by jonathanchamberlain** [comment]
Is that something I need to do, and if so how?

**Comment by asamborski** [comment]
From your fork of the repo, just move your file into _posts (should be as simple as **mv your-file _posts**)

**Comment by jonathanchamberlain** [comment]
I'm not seeing where I can do that. I'm just going to create a new pull request in the correct folder.

**Pull request merged**
